controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - Joint_wheel1
      - Joint_wheel2
      - Joint_wheel3
      - Joint_wheel4

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Joint_wheel1
      - Joint_wheel2
      - Joint_wheel3
      - Joint_wheel4

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 10.0
    action_monitor_rate: 10.0
