controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Joint_arm2
      - Joint_arm3
      - Joint_arm4
      - Joint_arm5

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 10.0
    action_monitor_rate: 10.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - Joint_arm1
      - Joint_arm2
      - Joint_arm3
      - Joint_arm4
      - Joint_arm5
      - Joint_arm6
      - Joint_grasp_point