### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 10.0
        two_d_mode: true
        publish_acceleration: true
        publish_tf: true

        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" ifunspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified

        odom0: /base_diff_controller/odom
        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, true,
                       false, false, true,
                       false, false, false]
