function T = trans(a,alpha,d,theta)

T_alpha = [1, 0,           0,            0;...
           0, cosd(alpha), -sind(alpha), 0;...
           0, sind(alpha), cosd(alpha),  0;...
           0, 0,           0,            1];

T_a = [1, 0, 0, a;...
       0, 1, 0, 0;...
       0, 0, 1, 0;...
       0, 0, 0, 1];

T_theta = [cosd(theta), -sind(theta), 0, 0;...
           sind(theta), cosd(theta),  0, 0;...
           0,           0,            1, 0;...
           0,           0,            0, 1];

T_d = [1, 0, 0, 0;...
       0, 1, 0, 0;...
       0, 0, 1, d;...
       0, 0, 0, 1];

T = T_alpha * T_a * T_theta * T_d;

end